plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}
android {
    namespace 'uk.mr_biz.fourlink.caller'
    compileSdk 36
    defaultConfig {
        applicationId 'uk.mr_biz.fourlink.caller'
        minSdk 33
        targetSdk 36
        versionCode 1
        versionName '1'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlin { jvmToolchain(17) }
}
dependencies {
    implementation project(':fourlink')
}
